name: Workflow dispatch test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name to greet"

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello ${{ github.event.inputs.name }}!"
